apiVersion: v1

kind: ConfigMap

metadata:

  name: wordpress-config

data:

  WORDPRESS_DATABASE_HOST: {{ .Values.wordpress.wordpress_host }}

  WORDPRESS_DATABASE_USER: {{ .Values.wordpress.wordpress_user }}

  WORDPRESS_DATABASE_NAME: {{ .Values.wordpress.wordpress_database }}

---
apiVersion: v1

kind: Secret

metadata:

  name: wordpress-secrets

type: Opaque

data:
 WORDPRESS_DATABASE_PASSWORD: {{ .Values.wordpress.wordpress_password | b64enc | quote }}

